=== KolomboPulse/GOLD-6T-Tocken-list/dist/tokenlist.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://hardwaretor.com/tokenlist.json",
  "title": "Hardwaretor",
  "description": "Schema for lists of tokens compatible with the Uniswap Interface",
  "definitions": {
    "Version": {
      "type": "object",
      "description": "The version of the list, used in change detection",
      "examples": [
        {
          "major": 1,
          "minor": 0,
          "patch": 0
        }
      ],
      "additionalProperties": false,
      "properties": {
        "major": {
          "type": "integer",
          "description": "The major version of the list. Must be incremented when tokens are removed from the list or token addresses are changed.",
          "minimum": 0,
          "examples": [
            1,
            2
          ]
        },
        "minor": {
          "type": "integer",
          "description": "The minor version of the list. Must be incremented when tokens are added to the list.",
          "minimum": 0,
          "examples": [
            0,
            1
          ]
        },
        "patch": {
          "type": "integer",
          "description": "The patch version of the list. Must be incremented for any changes to the list.",
          "minimum": 0,
          "examples": [
            0,
            1
          ]
        }
      },
      "required": [
        "major",
        "minor",
        "patch"
      ]
    },
    "TagIdentifier": {
      "type": "string",
      "description": "The unique identifier of a tag",
      "minLength": 1,
      "maxLength": 10,
      "pattern": "^[\\w]+$",
      "examples": [
        "compound",
        "stablecoin"
      ]
    },
    "ExtensionIdentifier": {
      "type": "string",
      "description": "The name of a token extension property",
      "minLength": 1,
      "maxLength": 40,
      "pattern": "^[\\w]+$",
      "examples": [
        "color",
        "is_fee_on_transfer",
        "aliases"
      ]
    },
    "ExtensionMap": {
      "type": "object",
      "description": "An object containing any arbitrary or vendor-specific token metadata",
      "maxProperties": 10,
      "propertyNames": {
        "$ref": "#/definitions/ExtensionIdentifier"
      },
      "additionalProperties": {
        "$ref": "#/definitions/ExtensionValue"
      },
      "examples": [
        {
          "color": "#000000",
          "is_verified_by_me": true
        },
        {
          "x-bridged-addresses-by-chain": {
            "1": {
              "bridgeAddress": "0x4200000000000000000000000000000000000010",
              "tokenAddress": "0x4200000000000000000000000000000000000010"
            }
          }
        }
      ]
    },
    "ExtensionPrimitiveValue": {
      "anyOf": [
        {
          "type": "string",
          "minLength": 1,
          "maxLength": 42,
          "examples": [
            "#00000"
          ]
        },
        {
          "type": "boolean",
          "examples": [
            true
          ]
        },
        {
          "type": "number",
          "examples": [
            15
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "ExtensionValue": {
      "anyOf": [
        {
          "$ref": "#/definitions/ExtensionPrimitiveValue"
        },
        {
          "type": "object",
          "maxProperties": 10,
          "propertyNames": {
            "$ref": "#/definitions/ExtensionIdentifier"
          },
          "additionalProperties": {
            "$ref": "#/definitions/ExtensionValueInner0"
          }
        }
      ]
    },
    "ExtensionValueInner0": {
      "anyOf": [
        {
          "$ref": "#/definitions/ExtensionPrimitiveValue"
        },
        {
          "type": "object",
          "maxProperties": 10,
          "propertyNames": {
            "$ref": "#/definitions/ExtensionIdentifier"
          },
          "additionalProperties": {
            "$ref": "#/definitions/ExtensionValueInner1"
          }
        }
      ]
    },
    "ExtensionValueInner1": {
      "anyOf": [
        {
          "$ref": "#/definitions/ExtensionPrimitiveValue"
        }
      ]
    },
    "TagDefinition": {
      "type": "object",
      "description": "Definition of a tag that can be associated with a token via its identifier",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the tag",
          "pattern": "^[ \\w]+$",
          "minLength": 1,
          "maxLength": 20
        },
        "description": {
          "type": "string",
          "description": "A user-friendly description of the tag",
          "pattern": "^[ \\w\\.,:]+$",
          "minLength": 1,
          "maxLength": 200
        }
      },
      "required": [
        "name",
        "description"
      ],
      "examples": [
        {
          "name": "Hardwaretor",
          "description": "AI Generative Hardware Designer"
        }
      ]
    },
    "TokenInfo": {
      "type": "object",
      "description": "Hardwaretor",
      "additionalProperties": false,
      "properties": {
        "chainId": {
          "type": "integer",
          "description": "1",
          "minimum": 1,
          "examples": [
            1
            
          ]
        },
        "address": {
          "type": "string",
          "description": "The checksummed address of the token on the specified chain ID",
          "pattern": "^0x[a-fA-F0-9]{40}$",
          "examples": [
            "0x63eC86fC38A0021FCF4980ADA380FF82c7859788"
          ]
        },
        "decimals": {
          "type": "integer",
          "description": "The number of decimals for the token balance",
          "minimum": 0,
          "maximum": 255,
          "examples": [
            18
          ]
        },
        "name": {
          "type": "string",
          "description": "The name of the token",
          "minLength": 0,
          "maxLength": 60,
          "anyOf": [
            {
              "const": ""
            },
            {
              "pattern": "^[ \\S+]+$"
            }
          ],
          "examples": [
            "Hardwaretor"
          ]
        },
        "symbol": {
          "type": "string",
          "description": "The symbol for the token",
          "minLength": 0,
          "maxLength": 20,
          "anyOf": [
            {
              "const": ""
            },
            {
              "pattern": "^\\S+$"
            }
          ],
          "examples": [
            "HAW"
          ]
        },
        "logoURI": {
          "type": "string",
          "description": "A URI to the token logo asset; if not set, interface will attempt to find a logo based on the token address; suggest SVG or PNG of size 64x64",
          "format": "uri",
          "examples": [
            "ipfs://QmfMAg7QATrPb3wdYzefkPW8Hb3PYg5PLxGwG5XKgUrYHg"
          ]
        },
        "tags": {
          "type": "array",
          "description": "An array of tag identifiers associated with the token; tags are defined at the list level",
          "items": {
            "$ref": "#/definitions/TagIdentifier"
          },
          "maxItems": 10,
          "examples": [
            "stablecoin",
            "compound"
          ]
        },
        "extensions": {
          "$ref": "#/definitions/ExtensionMap"
        }
      },
      "required": [
        "chainId",
        "address",
        "decimals",
        "name",
        "symbol"
      ]
    }
  },
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "Hardwaretor",
      "minLength": 1,
      "maxLength": 30,
      "pattern": "^[\\w ]+$",
      "examples": [
        "Hardwaretor"
      ]
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "description": "The timestamp of this list version; i.e. when this immutable version of the list was created"
    },
    "version": {
      "$ref": "#/definitions/Version"
    },
    "tokens": {
      "type": "array",
      "description": "The list of tokens included in the list",
      "items": {
        "$ref": "#/definitions/TokenInfo"
      },
      "minItems": 1,
      "maxItems": 10000
    },
    "tokenMap": {
      "type": "object",
      "description": "A mapping of key 'chainId_tokenAddress' to its corresponding token object",
      "minProperties": 1,
      "maxProperties": 10000,
      "propertyNames": {
        "type": "string"
      },
      "additionalProperties": {
        "$ref": "#/definitions/TokenInfo"
      },
      "examples": [
        {
          "4_0x63eC86fC38A0021FCF4980ADA380FF82c7859788":  {
            "name": "Hardwaretor",
            "address": "0x63eC86fC38A0021FCF4980ADA380FF82c7859788",
            "symbol": "HAW",
            "decimals": 18,
            "chainId": 1,
            "logoURI": "ipfs://QmfMAg7QATrPb3wdYzefkPW8Hb3PYg5PLxGwG5XKgUrYHg"
          }
        }
      ]
    },
    "keywords": {
      "type": "array",
      "description": "Keywords associated with the contents of the list; may be used in list discoverability",
      "items": {
        "type": "string",
        "description": "A keyword to describe the contents of the list",
        "minLength": 1,
        "maxLength": 20,
        "pattern": "^[\\w ]+$",
        "examples": [
          "compound",
          "lending",
          "personal tokens"
        ]
      },
      "maxItems": 20,
      "uniqueItems": true
    },
    "tags": {
      "type": "object",
      "description": "A mapping of tag identifiers to their name and description",
      "propertyNames": {
        "$ref": "#/definitions/TagIdentifier"
      },
      "additionalProperties": {
        "$ref": "#/definitions/TagDefinition"
      },
      "maxProperties": 20,
      "examples": [
        {
          "stablecoin": {
            "name": "Hardwaretor",
            "description": "AI Generative Hardware Designer"
          }
        }
      ]
    },
    "logoURI": {
      "type": "string",
      "description": "Hardwaretor Logo",
      "format": "uri",
      "examples": [
        "ipfs://QmfMAg7QATrPb3wdYzefkPW8Hb3PYg5PLxGwG5XKgUrYHg"
      ]
    }
  },
  "required": [
    "name",
    "timestamp",
    "version",
    "tokens"
  ]
}

=== KolomboPulse/GOLD-6T-Tocken-list/src/JODC.tokenlist.json
{
  "name": "My Token List",
  "timestamp": "2021-09-16T00:00:00+00:00",
  "tokens": [
    {
      "chainId": 1,
      "address": "8n5MZZr6RrtBhqM8H5qCKxQwZD5VJzVVZ6vVjiRCx7sL",
      "decimals": 6,
      "name": "Jordanian Dinar Digital Currency",
      "tags":["stable coin", "A token with value pegged to the value of Jordanian Dinar in 1 to 1"],
      "logoURI":"https://cdn.jsdelivr.net/gh/baselm/JODC@main/JODC_logo.png",
      "symbol": "JODC"
    }
  ],
  "version": {
    "major": 1,
    "minor": 0,
    "patch": 0
  }
}

=== KolomboPulse/GOLD-6T-Tocken-list/test/schema/example-name-symbol-special-characters.tokenlist.json
{
  "name": "My Token List",
  "timestamp": "2020-06-12T00:00:00+00:00",
  "tokens": [
    {
      "chainId": 1,
      "address": "0x9A48BD0EC040ea4f1D3147C025cd4076A2e71e3e",
      "symbol": "USD++",
      "name": "PieDAO USD++ Pool",
      "decimals": 18
    },
    {
      "chainId": 1,
      "address": "0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc",
      "symbol": "UNI-USDC/ETH+50/50%",
      "name": "Uniswap V2-USDC/ETH+50/50%",
      "decimals": 18
    },
    {
      "chainId": 1,
      "address": "0x9A48BD0EC040ea4f1D3147C025cd4076A2e71e3e",
      "symbol": "DIACRITIC",
      "name": "Ázertíyuöp",
      "decimals": 18
    }
  ],
  "version": {
    "major": 1,
    "minor": 0,
    "patch": 0
  }
}
